package formation.persistence.entities;
// Generated 15 avr. 2021 à 11:09:42 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "ADRESSE", schema = "GESTION")
public class Adresse implements java.io.Serializable {

	private BigDecimal idadresse;
	private String numeroadresse;
	private String rueadresse;
	private String villeadresse;
	private String cpadresse;
	private Set<Client> clients = new HashSet<Client>(0);

	public Adresse() {
	}

	public Adresse(BigDecimal idadresse) {
		this.idadresse = idadresse;
	}

	public Adresse(BigDecimal idadresse, String numeroadresse, String rueadresse, String villeadresse, String cpadresse,
			Set<Client> clients) {
		this.idadresse = idadresse;
		this.numeroadresse = numeroadresse;
		this.rueadresse = rueadresse;
		this.villeadresse = villeadresse;
		this.cpadresse = cpadresse;
		this.clients = clients;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "adresse_generator")
	@SequenceGenerator(name="adresse_generator", sequenceName = "adresse_seq", allocationSize=1)
	@Column(name = "IDADRESSE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdadresse() {
		return this.idadresse;
	}

	public void setIdadresse(BigDecimal idadresse) {
		this.idadresse = idadresse;
	}

	@Column(name = "NUMEROADRESSE", length = 1016)
	public String getNumeroadresse() {
		return this.numeroadresse;
	}

	public void setNumeroadresse(String numeroadresse) {
		this.numeroadresse = numeroadresse;
	}

	@Column(name = "RUEADRESSE", length = 1016)
	public String getRueadresse() {
		return this.rueadresse;
	}

	public void setRueadresse(String rueadresse) {
		this.rueadresse = rueadresse;
	}

	@Column(name = "VILLEADRESSE", length = 1016)
	public String getVilleadresse() {
		return this.villeadresse;
	}

	public void setVilleadresse(String villeadresse) {
		this.villeadresse = villeadresse;
	}

	@Column(name = "CPADRESSE", length = 1016)
	public String getCpadresse() {
		return this.cpadresse;
	}

	public void setCpadresse(String cpadresse) {
		this.cpadresse = cpadresse;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "adresse")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
