package formation.persistence.entities;
// Generated 15 avr. 2021 à 11:09:42 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "CLIENT", schema = "GESTION")
public class Client implements java.io.Serializable {

	private BigDecimal idclient;
	private Stockuser stockuser = new Stockuser();
	private Adresse adresse = new Adresse();
	private String civiliteclient;
	private String nomclient;
	private String prenomclient;
	private Date datenaissanceclient;
	private String emailclient;
	private String telclient;
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Client() {
	}

	public Client(BigDecimal idclient) {
		this.idclient = idclient;
	}

	public Client(BigDecimal idclient, Stockuser stockuser, Adresse adresse, String civiliteclient, String nomclient,
			String prenomclient, Date datenaissanceclient, String emailclient, String telclient,
			Set<Commande> commandes) {
		this.idclient = idclient;
		this.stockuser = stockuser;
		this.adresse = adresse;
		this.civiliteclient = civiliteclient;
		this.nomclient = nomclient;
		this.prenomclient = prenomclient;
		this.datenaissanceclient = datenaissanceclient;
		this.emailclient = emailclient;
		this.telclient = telclient;
		this.commandes = commandes;
	}

	@Id

	@Column(name = "IDCLIENT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdclient() {
		return this.idclient;
	}

	public void setIdclient(BigDecimal idclient) {
		this.idclient = idclient;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "IDUSER")
	public Stockuser getStockuser() {
		return this.stockuser;
	}

	public void setStockuser(Stockuser stockuser) {
		this.stockuser = stockuser;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "IDADRESSE")
	public Adresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Adresse adresse) {
		this.adresse = adresse;
	}

	@Column(name = "CIVILITECLIENT", length = 1016)
	public String getCiviliteclient() {
		return this.civiliteclient;
	}

	public void setCiviliteclient(String civiliteclient) {
		this.civiliteclient = civiliteclient;
	}

	@Column(name = "NOMCLIENT", length = 1016)
	public String getNomclient() {
		return this.nomclient;
	}

	public void setNomclient(String nomclient) {
		this.nomclient = nomclient;
	}

	@Column(name = "PRENOMCLIENT", length = 1016)
	public String getPrenomclient() {
		return this.prenomclient;
	}

	public void setPrenomclient(String prenomclient) {
		this.prenomclient = prenomclient;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATENAISSANCECLIENT", length = 7)
	public Date getDatenaissanceclient() {
		return this.datenaissanceclient;
	}

	public void setDatenaissanceclient(Date datenaissanceclient) {
		this.datenaissanceclient = datenaissanceclient;
	}

	@Column(name = "EMAILCLIENT", length = 1016)
	public String getEmailclient() {
		return this.emailclient;
	}

	public void setEmailclient(String emailclient) {
		this.emailclient = emailclient;
	}

	@Column(name = "TELCLIENT", length = 1016)
	public String getTelclient() {
		return this.telclient;
	}

	public void setTelclient(String telclient) {
		this.telclient = telclient;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "client")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
