package formation.persistence.entities;
// Generated 15 avr. 2021 � 11:09:42 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "COMMANDE", schema = "GESTION")
public class Commande implements java.io.Serializable {

	private CommandeId id;
	private Client client = new Client();
	private Etat etat = new Etat();
	private Produit produit = new Produit();
	private Date datecommande;
	private BigDecimal qtecommande;

	public Commande() {
	}

	public Commande(CommandeId id, Client client, Produit produit) {
		this.id = id;
		this.client = client;
		this.produit = produit;
	}

	public Commande(CommandeId id, Client client, Etat etat, Produit produit, Date datecommande,
			BigDecimal qtecommande) {
		this.id = id;
		this.client = client;
		this.etat = etat;
		this.produit = produit;
		this.datecommande = datecommande;
		this.qtecommande = qtecommande;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idclient", column = @Column(name = "IDCLIENT", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idproduit", column = @Column(name = "IDPRODUIT", nullable = false, precision = 22, scale = 0)) })
	public CommandeId getId() {
		this.id = new CommandeId(this.client.getIdclient(), this.produit.getIdproduit());
		return this.id;
	}

	public void setId(CommandeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDCLIENT", nullable = false, insertable = false, updatable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDETAT")
	public Etat getEtat() {
		return this.etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDPRODUIT", nullable = false, insertable = false, updatable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECOMMANDE", length = 7)
	public Date getDatecommande() {
		return this.datecommande;
	}

	public void setDatecommande(Date datecommande) {
		this.datecommande = datecommande;
	}

	@Column(name = "QTECOMMANDE", precision = 22, scale = 0)
	public BigDecimal getQtecommande() {
		return this.qtecommande;
	}

	public void setQtecommande(BigDecimal qtecommande) {
		this.qtecommande = qtecommande;
	}

}
