package formation.persistence.entities;
// Generated 15 avr. 2021 à 11:09:42 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "ROLE", schema = "GESTION")
public class Role implements java.io.Serializable {

	private BigDecimal idrole;
	private String typerole;
	private Set<Stockuser> stockusers = new HashSet<Stockuser>(0);

	public Role() {
	}

	public Role(BigDecimal idrole) {
		this.idrole = idrole;
	}

	public Role(BigDecimal idrole, String typerole, Set<Stockuser> stockusers) {
		this.idrole = idrole;
		this.typerole = typerole;
		this.stockusers = stockusers;
	}

	@Id

	@Column(name = "IDROLE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdrole() {
		return this.idrole;
	}

	public void setIdrole(BigDecimal idrole) {
		this.idrole = idrole;
	}

	@Column(name = "TYPEROLE", length = 80)
	public String getTyperole() {
		return this.typerole;
	}

	public void setTyperole(String typerole) {
		this.typerole = typerole;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "role")
	public Set<Stockuser> getStockusers() {
		return this.stockusers;
	}

	public void setStockusers(Set<Stockuser> stockusers) {
		this.stockusers = stockusers;
	}

}
